# How to do eigenvalue placement

Do all imports:

In [1]:
import numpy as np
from scipy import linalg
from scipy import signal # <-- NEW

Define state-space model:

In [2]:
A = np.array([[0., 1.], [2., 0.]])
B = np.array([[0.], [1.]])

Choose desired locations of closed-loop eigenvalues:

In [13]:
p = [-1., -4.]

Choose gain matrix to place closed-loop eigenvalues at desired locations:

In [14]:
result = signal.place_poles(A, B, p)

Use `vars` to look at what is returned by `signal.place_poles`:

In [15]:
vars(result)

{'gain_matrix': array([[6., 5.]]),
 'computed_poles': array([-4., -1.]),
 'requested_poles': array([-4., -1.]),
 'X': array([[-0.24253563+0.j, -0.70710678+0.j],
        [ 0.9701425 +0.j,  0.70710678+0.j]]),
 'rtol': 0,
 'nb_iter': 0}

Extract and show the gain matrix:

In [16]:
K = result.gain_matrix

print(K)

[[6. 5.]]


Get the gain matrix in one line if we want:

In [17]:
K = signal.place_poles(A, B, p).gain_matrix

print(K)

[[6. 5.]]


In [11]:
p = [-2e6, -1e6]
K = signal.place_poles(A, B, p).gain_matrix

print(K)

[[2.e+12 3.e+06]]


Verify that the gain matrix puts eigenvalues in desired locations:

In [18]:
linalg.eigvals(A - B @ K)

array([-1.+0.j, -4.+0.j])

Ask for eigenvalues with non-zero imaginary part:

In [19]:
p = [-2. + 1j * 3., -2. - 1j * 3.]
K = signal.place_poles(A, B, p).gain_matrix

print(K)

[[15.  4.]]


In [20]:
linalg.eigvals(A - B @ K)

array([-2.+3.j, -2.-3.j])

You can't ask for a complex eigenvalue without also asking for it complex conjugate. (This is true for any method of eigenvalue placement.)

In [21]:
p = [-2. + 1j * 3., -4.]
K = signal.place_poles(A, B, p).gain_matrix

print(K)

ValueError: Complex poles must come with their conjugates

You can't ask for multiple eigenvalues at the same location. (This is true only for `place_poles`, not in general.)

In [22]:
p = [-1., -1.]
K = signal.place_poles(A, B, p).gain_matrix

print(K)

ValueError: at least one of the requested pole is repeated more than rank(B) times